version: "2"

services:
    ola:
        build: .
        image: seetalchile/olaserver:latest
        volumes:
            - ./config:/root/.ola
        ports:
            - "6454:6454"
            - "9010:9010"
            - "9090:9090"
        network_mode: host

